[project]
name = "logboard"
version = "0.1.0"
description = "A lightweight structured log viewer with live streaming and filters."
authors = [{ name = "Thibaut Lamadon" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "uvicorn",
    "jinja2",
    "typer"
]

[project.scripts]
logboard = "logboard.cli:app"
